# Standard n8n setup for DBMS with n8n

version: '3.8'

volumes:
  n8n_storage:
  mysql_storage:
  uploads_storage:

networks:
  dbms:

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    networks: ['dbms']
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-church_members}
      - MYSQL_USER=${MYSQL_USER:-church_user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-church_password}
    volumes:
      - mysql_storage:/var/lib/mysql
      - ./assets/church_management.sql:/docker-entrypoint-initdb.d/church_management.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: adminer
    networks: ['dbms']
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    networks: ['dbms']
    restart: unless-stopped
    environment:
      - DB_TYPE=mysqldb
      - DB_MYSQLDB_HOST=mysql
      - DB_MYSQLDB_USER=root
      - DB_MYSQLDB_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - DB_MYSQLDB_DATABASE=n8n_db
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY:-your-encryption-key-here}
      - N8N_USER_MANAGEMENT_JWT_SECRET=${N8N_USER_MANAGEMENT_JWT_SECRET:-your-jwt-secret-here}
      - N8N_CORS_ENABLED=true
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    ports:
      - "5678:5678"
    volumes:
      - n8n_storage:/home/node/.n8n
      - uploads_storage:/data/uploads
    depends_on:
      mysql:
        condition: service_healthy

  # React Frontend
  frontend:
    build: .
    container_name: dbms-frontend
    networks: ['dbms']
    environment:
      - VITE_N8N_WEBHOOK_URL=http://localhost:5678/webhook-test/db/ruwi_church
      - VITE_N8N_IMAGE_URL=http://localhost:5678/webhook-test/uploads
    ports:
      - "3000:3000"
    depends_on:
      - n8n
    restart: unless-stopped